sequence = input("Введите последовательность ДНК (A, T, G, C): ").upper()
length = len(sequence)
a_count = sequence.count('A')
t_count = sequence.count('T')
g_count = sequence.count('G')
c_count = sequence.count('C')
print("\tАнализ последовательности ДНК")
print(f"\nКоличество нуклеотидов:")
print(f"A: {a_count}", f"\nT: {t_count}", f"\nG: {g_count}", f"\nC: {c_count}")
print(f"\nПроцентное содержание:")
print(f"T: {(a_count/length)*100:.1f}%", f"\nT: {(t_count/length)*100:.1f}%", f"\nT: {(g_count/length)*100:.1f}%", f"\nT: {(c_count/length)*100:.1f}%")
print(f"\nДлина последовательности: {length}")